# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookReview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookReview
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire', '~> 5.5'
pod 'Kingfisher', '~> 7.0'

  target 'BookReviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookReviewUITests' do
    # Pods for testing
  end

end
