# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyLoginPage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyLoginPage
	pod 'Firebase/Auth'
	pod 'GoogleSignIn','~> 5.0.2'

  target 'SpotifyLoginPageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyLoginPageUITests' do
    # Pods for testing
  end

end
