# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindConvenienceStoreApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindConvenienceStoreApp
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit' 
target 'FindConvenienceStoreAppTests' do 
	pod 'Stubber'
	pod 'Nimble'
	pod 'RxBlocking'
	pod 'RxTest'
end

end
